[PHP]
display_errors = On
display_startup_errors = On
log_errors = On
error_log = /var/log/php/error.log
error_reporting = E_ALL
memory_limit = 512M
max_execution_time = 60
max_input_time = 60
post_max_size = 50M
upload_max_filesize = 50M
default_charset = UTF-8

[Date]
date.timezone = Asia/Kolkata

[mysqli]
mysqli.max_connections = 20

[Xdebug]
xdebug.mode = debug
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 256
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 10000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0
