[www]
user = www-data
group = www-data
listen = 9000

pm = dynamic
pm.max_children = 20
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 10

pm.max_requests = 1000
pm.process_idle_timeout = 10s

clear_env = no

catch_workers_output = yes
decorate_workers_output = no

slowlog = /var/log/php/slow.log
slowlog.timeout = 5s

request_slowlog_timeout = 10s

php_admin_value[error_log] = /var/log/php/error.log
php_admin_flag[log_errors] = on
